### ISSUE TITLE
Error: Failed to execute transaction: Transaction processing for endorser [localhost:7051]: Chaincode status Code: (500) UNKNOWN. Description: failed to execute contract: call error: REVERT not yet fully implemented

### ISSUE THREAD

**Issue by gnurtcouq** [IBM/loyalty-points-evm-fabric#12]
Hi All,
I have successfully registered a Partner and a Member into the Network. I managed to login as the new Member, then select a Partner using drop-down list . When I click the button "Purchase Item X for $20 and earn 30 points", there is error in the console:

node app.js

app running on port: 8000
Getting the Contract
Got address: 0d2dc1658066c63ab46d2f772b7e2074766d4350
Getting the Contract
AccountCode: 0xd5c456b7218e9d11c577bd015c61aee93458157f
memberData:0xd5c456b7218e9d11c577bd015c61aee93458157f,Hong,Le,le@yahoo.com,0,true
Getting the Contract
Got address: d9da3fc47ff1d292d1eba3338ab68636bf20a6e7
Getting the Contract
Got address: d9da3fc47ff1d292d1eba3338ab68636bf20a6e7
Using param - points: 30 partnerAddress: 0x64602e1922b94c026785cdd5ea729822bc1207a4
Getting the Contract
Got address: d9da3fc47ff1d292d1eba3338ab68636bf20a6e7
Error: Failed to execute transaction: Transaction processing for endorser [localhost:7051]: Chaincode status Code: (500) UNKNOWN. Description: failed to execute contract: call error: REVERT not yet fully implemented
    at Object.InvalidResponse (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/node_modules/web3/lib/web3/errors.js:38:16)
    at RequestManager.send (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.send [as sendTransaction] (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/node_modules/web3/lib/web3/method.js:145:58)
    at SolidityFunction.sendTransaction (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/node_modules/web3/lib/web3/function.js:170:26)
    at SolidityFunction.execute (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/node_modules/web3/lib/web3/function.js:256:37)
    at Object.earnPoints (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/dapp.js:627:33)
    at /home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/app.js:180:25
    at Layer.handle [as handle_request] (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/trung/go/src/github.com/hyperledger/loyalty-points-evm-fabric/web-app/node_modules/express/lib/router/route.js:112:3)

**Comment by raheelzubairy** [comment]
@gnurtcouq I was unable to recreate the error and the app worked good .  The error seems to imply its originating from the [sol contract](https://github.com/IBM/loyalty-points-evm-fabric/blob/master/LoyaltyPoints.sol#L68).  Could you ensure the partner is correctly registered.

**Comment by gnurtcouq** [comment]
@raheelzubairy the partner is correctly registered.

One question is how to switch b/t Member/Partner Sign-in? If I change dapp.js as below (according to your file "Updated README for Fabric v1.4 ":

//github.com/IBM/hyperledger-fabric-evm-demo/blob/master/src/dapp.js
const Web3 = require('web3');
var contractAddress = '8772a9143882e551845db9fafa1c6b1a0b596388';
var provider = "http://localhost:5000";
var contractAddress = '30a5c90d8593a94a89fdcb7a5e2aeb065f18b7af';
var provider = "http://localhost:5001";
...

When I access the URL=http://localhost:8000 it always said that "You are registered as Member on the network"?

**Comment by raheelzubairy** [comment]
@gnurtcouq try running first with the provider as "http://localhost:5000" for Partner, and then as "http://localhost:5001" for Member.  It should not be repeated.  The **contractAddress** should be the same in both cases.

**Comment by gnurtcouq** [comment]
@raheelzubairy: you mean I still using http://localhost:8000/ to open the app in both case?

**Comment by raheelzubairy** [comment]
@gnurtcouq yeah, it would be the same port but accessing different identities.  You can update the [port here](https://github.com/IBM/loyalty-points-evm-fabric/blob/master/web-app/app.js#L257) for the second app.

**Comment by gnurtcouq** [comment]
@raheelzubairy : Great ! Now the app is working. In reality there should be 2 Fab3 setup in 2 different box so there is no need to change the provider? How can I achieve this (setting 2 Fab3 into 2 different servers)

**Comment by raheelzubairy** [comment]
@gnurtcouq you can run the same web-app as two copies with different port numbers.  Each app with a unique port and different provider Fab3

**Comment by gnurtcouq** [comment]
@raheelzubairy thanks a lot for the help. In case I have multiple members, who want to resister/connect to the network in the same time, how can I setup the environment? Because in the current setup, whenever I login to  http://localhost:8000 it always informs that "You are registered as Member on the network"

**Comment by raheelzubairy** [comment]
@gnurtcouq NP. You can change the port number to try a different port number like http://localhost:8001 and so forth

**Comment by gnurtcouq** [comment]
@raheelzubairy : I tried to change the port number (e.g. try a different port number like http://localhost:8001) but when login the app using http://localhost:8001, it said "You are registered as Member on the network". It's seem that the codes allows only a single member login the network. Any idea how to change the code to allow multiple members login?

**Comment by horeaporutiu** [comment]
closing due to inactivity.
